services:
  - type: web
    name: flask-selenium-app
    env: python
    buildCommand: "./install-chrome.sh && pip install -r requirements.txt"
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
